name = "a0b_stm32h723_selftest"
description = "A0B STM32H723 sefltest"
version = "0.1.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"

project-files = ["a0b_stm32h723_selftest.gpr"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[configuration.values]
a0b_armv7m.fpu_extension = "VFPv5"

[[depends-on]]
a0b_stm32h723 = "*"

[[pins]]
a0b_stm32h723 = { path='..' }
