name = "a0b_svd_stm32h723"
description = "A0B: STM32H723 SVD package"
version = "0.1.0"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"

project-files=["gnat/a0b_svd_stm32h723.gpr"]

tags = ["embedded", "svd", "stm32", "stm32h7", "stm32h723"]

[configuration]
disabled = true

[[depends-on]]
gnat_arm_elf = "*"
a0b_base = "*"
