name = "a0b_stm32h723"
description = "STM32H723 base and SVD package"
website = "https://github.com/godunko/a0b-stm32h723"
version = "0.1.0"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"

project-files=["gnat/a0b_stm32h723.gpr"]

tags = ["a0b", "embedded", "svd", "stm32", "stm32h7", "stm32h723"]

[configuration]
disabled = true

[[depends-on]]
a0b_base = "*"
a0b_armv7m = "*"
gnat_arm_elf = "*"
